Models/Participante.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AAPC.Models
{
    public class Participante
    {
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Nome { get; set; }
        public string Sobrenome { get; set; }

        [Display(Name = "Nascimento")]
        [DataType(DataType.Date)]
        public DateTime Nascimento { get; set; }
        
        public string DiaDoTreino { get; set; }
        //public DayOfWeek DayOfWeek { get; set; }

       // public string Telefone { get; set; }
       // public string Endereco { get; set; }
       // public string Bairro { get; set; }
       // public string Cidade { get; set; }
       // public string CEP { get; set; }
       
    }
}

Controllers/ParticipantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AAPC.Data;
using AAPC.Models;

namespace AAPC.Controllers
{
    public class ParticipantesController : Controller
    {
        private readonly MvcAAPCContext _context;

        public ParticipantesController(MvcAAPCContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string treinoP, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> treinoQuery = from t in _context.Participante
                                            orderby t.DiaDoTreino
                                            select t.DiaDoTreino;

            var participantes = from p in _context.Participante
                         select p;

            if (!string.IsNullOrEmpty(searchString))
            {
                participantes = participantes.Where(s => s.Nome.Contains(searchString));
            }
            
                     /*   if (!string.IsNullOrEmpty(treinoP))
                        {
                            participantes = participantes.Where(x => x.DiaDoTreino == treinoP);
                        }*/
            
            var treinoVM = new TreinoViewModel
            {
                Treinos = new SelectList(await treinoQuery.Distinct().ToListAsync()),
                LParticipantes = await participantes.ToListAsync()
            };

            return View(treinoVM);
        }

        // GET: Participantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participante
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participante == null)
            {
                return NotFound();
            }

            return View(participante);
        }

        // GET: Participantes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Participantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,Nascimento,DiaDoTreino")] Participante participante)
        {
            if (ModelState.IsValid) //,GeneroParticipante,Telefone,Endereco,Bairro,Cidade,CEP
            {
                _context.Add(participante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(participante);
        }

        // GET: Participantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participante.FindAsync(id);
            if (participante == null)
            {
                return NotFound();
            }
            return View(participante);
        }

        // POST: Participantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,Nascimento,DiaDoTreino")] Participante participante)
        {
            if (id != participante.Id) //,GeneroParticipante,Telefone,Endereco,Bairro,Cidade,CEP
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipanteExists(participante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(participante);
        }

        // GET: Participantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participante
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participante == null)
            {
                return NotFound();
            }

            return View(participante);
        }

        // POST: Participantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participante = await _context.Participante.FindAsync(id);
            _context.Participante.Remove(participante);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParticipanteExists(int id)
        {
            return _context.Participante.Any(e => e.Id == id);
        }
    }
}

Views/Participantes/Create.cshtml
@model AAPC.Models.Participante

@{
    ViewData["Title"] = "Create";
}

<!-- <h1>Create</h1> -->

<h4>Participante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaDoTreino" class="control-label">Dia do Treino</label>
                <input asp-for="DiaDoTreino" class="form-control" placeholder="Terça, Quinta ou Sábado" />
                <span asp-validation-for="DiaDoTreino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Participantes/Delete.cshtml
@model AAPC.Models.Participante

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Participante</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiaDoTreino)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaDoTreino)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Participantes/Details.cshtml
@model AAPC.Models.Participante

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Participante</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiaDoTreino)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaDoTreino)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Participantes/Edit.cshtml
@model AAPC.Models.Participante

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Participante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DiaDoTreino" class="control-label"></label>
                <input asp-for="DiaDoTreino" class="form-control" />
                <span asp-validation-for="DiaDoTreino" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Participantes/Index.cshtml
@model AAPC.Models.TreinoViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Participantes:</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Participantes" asp-action="Index" method="get">
    <p>
        <!-- <select asp-for="TreinoParticipante" asp-items="Model.Treinos">
             <option value="">All</option>
    </select>-->
        Dia:
        <input type="text" asp-for="SearchString" />
        <input type="submit" value="Buscar" />
    </p>

</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LParticipantes[0].Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LParticipantes[0].Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LParticipantes[0].Nascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LParticipantes[0].DiaDoTreino)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LParticipantes)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaDoTreino)
            </td>

            <td>
                <!-- <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |-->
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>