Models/Treino.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AAPC.Models
{
    public class Treino
    {
        public int Id { get; set; }
        public string Dia { get; set; }
        public string Horario { get; set; }
        public string Local { get; set; }
    }
}

Models/TreinoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using AAPC.Models;
using System;

namespace AAPC.Models
{
    public class TreinoViewModel
    {
        public List<Participante> LParticipantes { get; set; }
        public List<TreinoTerca> LPTTerca { get; set; }
        public List<TreinoQuinta> LPTQuinta { get; set; }
        public List<TreinoSabado> LPTSabado { get; set; }

        public SelectList Treinos { get; set; }
        public string TreinoParticipante { get; set; }
        public string SearchString { get; set; }
    }
}

Controllers/TreinoQuintasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AAPC.Data;
using AAPC.Models;

namespace AAPC.Controllers
{
    public class TreinoQuintasController : Controller
    {
        private readonly MvcAAPCContext _context;

        public TreinoQuintasController(MvcAAPCContext context)
        {
            _context = context;
        }

        // GET: TreinoQuintas
        public async Task<IActionResult> Index(string treinoP, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> treinoQuery = from t in _context.ParticipanteTreinoQuinta
                                             orderby t.Nome
                                             select t.Nome;

            var treinoQuintaParticipantes = from p in _context.ParticipanteTreinoQuinta
                                            select p;

            if (!string.IsNullOrEmpty(searchString))
            {
                treinoQuintaParticipantes = treinoQuintaParticipantes.Where(s => s.Nome.Contains(searchString));
            }

            /*   if (!string.IsNullOrEmpty(treinoP))
               {
                   participantes = participantes.Where(x => x.DiaDoTreino == treinoP);
               }*/

            var treinoVM = new TreinoViewModel
            {
                Treinos = new SelectList(await treinoQuery.Distinct().ToListAsync()),
                LPTQuinta = await treinoQuintaParticipantes.ToListAsync()
            };

            return View(treinoVM);
        }

        // GET: TreinoQuintas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TreinoQuintas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,Nascimento")] TreinoQuinta treinoQuinta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(treinoQuinta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(treinoQuinta);
        }

        // GET: TreinoQuintas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinoQuinta = await _context.ParticipanteTreinoQuinta.FindAsync(id);
            if (treinoQuinta == null)
            {
                return NotFound();
            }
            return View(treinoQuinta);
        }

        // POST: TreinoQuintas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,Nascimento")] TreinoQuinta treinoQuinta)
        {
            if (id != treinoQuinta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(treinoQuinta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreinoQuintaExists(treinoQuinta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(treinoQuinta);
        }

        // GET: TreinoQuintas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinoQuinta = await _context.ParticipanteTreinoQuinta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treinoQuinta == null)
            {
                return NotFound();
            }

            return View(treinoQuinta);
        }

        // POST: TreinoQuintas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var treinoQuinta = await _context.ParticipanteTreinoQuinta.FindAsync(id);
            _context.ParticipanteTreinoQuinta.Remove(treinoQuinta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TreinoQuintaExists(int id)
        {
            return _context.ParticipanteTreinoQuinta.Any(e => e.Id == id);
        }
    }
}

Controllers/TreinoSabadoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AAPC.Data;
using AAPC.Models;

namespace AAPC.Controllers
{
    public class TreinoSabadoesController : Controller
    {
        private readonly MvcAAPCContext _context;

        public TreinoSabadoesController(MvcAAPCContext context)
        {
            _context = context;
        }

        // GET: TreinoSabadoes
        public async Task<IActionResult> Index(string treinoP, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> treinoQuery = from t in _context.ParticipanteTreinoSabado
                                             orderby t.Nome
                                             select t.Nome;

            var treinoSabadoParticipantes = from p in _context.ParticipanteTreinoSabado
                                select p;

            if (!string.IsNullOrEmpty(searchString))
            {
                treinoSabadoParticipantes = treinoSabadoParticipantes.Where(s => s.Nome.Contains(searchString));
            }

            /*   if (!string.IsNullOrEmpty(treinoP))
               {
                   participantes = participantes.Where(x => x.DiaDoTreino == treinoP);
               }*/

            var treinoVM = new TreinoViewModel
            {
                Treinos = new SelectList(await treinoQuery.Distinct().ToListAsync()),
                LPTSabado = await treinoSabadoParticipantes.ToListAsync()
            };

            return View(treinoVM);
        }

        // GET: TreinoSabadoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participante = await _context.Participante
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participante == null)
            {
                return NotFound();
            }

            return View(participante);
        }

        // GET: TreinoSabadoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TreinoSabadoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,Nascimento")] TreinoSabado treinoSabado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(treinoSabado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(treinoSabado);
        }

        // GET: TreinoSabadoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinoSabado = await _context.ParticipanteTreinoSabado.FindAsync(id);
            if (treinoSabado == null)
            {
                return NotFound();
            }
            return View(treinoSabado);
        }

        // POST: TreinoSabadoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,Nascimento")] TreinoSabado treinoSabado)
        {
            if (id != treinoSabado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(treinoSabado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreinoSabadoExists(treinoSabado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(treinoSabado);
        }

        // GET: TreinoSabadoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinoSabado = await _context.ParticipanteTreinoSabado
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treinoSabado == null)
            {
                return NotFound();
            }

            return View(treinoSabado);
        }

        // POST: TreinoSabadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var treinoSabado = await _context.ParticipanteTreinoSabado.FindAsync(id);
            _context.ParticipanteTreinoSabado.Remove(treinoSabado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TreinoSabadoExists(int id)
        {
            return _context.ParticipanteTreinoSabado.Any(e => e.Id == id);
        }
    }
}

Controllers/TreinoTercasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AAPC.Data;
using AAPC.Models;

namespace AAPC.Controllers
{
    public class TreinoTercasController : Controller
    {
        private readonly MvcAAPCContext _context;

        public TreinoTercasController(MvcAAPCContext context)
        {
            _context = context;
        }

        // GET: TreinoTercas
        public async Task<IActionResult> Index(string treinoP, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> treinoQuery = from t in _context.ParticipanteTreinoTerca
                                             orderby t.Nome
                                             select t.Nome;

            var treinoTercaParticipantes = from p in _context.ParticipanteTreinoTerca
                                            select p;

            if (!string.IsNullOrEmpty(searchString))
            {
                treinoTercaParticipantes = treinoTercaParticipantes.Where(s => s.Nome.Contains(searchString));
            }

            /*   if (!string.IsNullOrEmpty(treinoP))
               {
                   participantes = participantes.Where(x => x.DiaDoTreino == treinoP);
               }*/

            var treinoVM = new TreinoViewModel
            {
                Treinos = new SelectList(await treinoQuery.Distinct().ToListAsync()),
                LPTTerca = await treinoTercaParticipantes.ToListAsync()
            };

            return View(treinoVM);
        }

        // GET: TreinoTercas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TreinoTercas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,Nascimento")] TreinoTerca treinoTerca)
        {
            if (ModelState.IsValid)
            {
                _context.Add(treinoTerca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(treinoTerca);
        }

        // GET: TreinoTercas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinoTerca = await _context.ParticipanteTreinoTerca.FindAsync(id);
            if (treinoTerca == null)
            {
                return NotFound();
            }
            return View(treinoTerca);
        }

        // POST: TreinoTercas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,Nascimento")] TreinoTerca treinoTerca)
        {
            if (id != treinoTerca.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(treinoTerca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreinoTercaExists(treinoTerca.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(treinoTerca);
        }

        // GET: TreinoTercas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinoTerca = await _context.ParticipanteTreinoTerca
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treinoTerca == null)
            {
                return NotFound();
            }

            return View(treinoTerca);
        }

        // POST: TreinoTercas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var treinoTerca = await _context.ParticipanteTreinoTerca.FindAsync(id);
            _context.ParticipanteTreinoTerca.Remove(treinoTerca);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TreinoTercaExists(int id)
        {
            return _context.ParticipanteTreinoTerca.Any(e => e.Id == id);
        }
    }
}

Views/Treinos/Create.cshtml
@model AAPC.Models.Treino

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Treino</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Dia" class="control-label"></label>
                <input asp-for="Dia" class="form-control" />
                <span asp-validation-for="Dia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horario" class="control-label"></label>
                <input asp-for="Horario" class="form-control" />
                <span asp-validation-for="Horario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Local" class="control-label"></label>
                <input asp-for="Local" class="form-control" />
                <span asp-validation-for="Local" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Treinos/Delete.cshtml
@model AAPC.Models.Treino

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Treino</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Local)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Local)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Treinos/Details.cshtml
@model AAPC.Models.Treino

@{
    ViewData["Title"] = "Details";
}

<h1>Treino de Terça</h1>

<div>
    <h4>Participantes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Local)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Local)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Treinos/Edit.cshtml
@model AAPC.Models.Treino

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Treino</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Dia" class="control-label"></label>
                <input asp-for="Dia" class="form-control" />
                <span asp-validation-for="Dia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horario" class="control-label"></label>
                <input asp-for="Horario" class="form-control" />
                <span asp-validation-for="Horario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Local" class="control-label"></label>
                <input asp-for="Local" class="form-control" />
                <span asp-validation-for="Local" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Treinos/Index.cshtml
@model IEnumerable<AAPC.Models.Treino>

@{ ViewData["Title"] = "Index"; }
    <body style="background: url('@Url.Content("~/Images/imgfundo.jpg")');">

        <div class="text-center">
            <h1>AAPC</h1>
            <h2>Amigos Apaixonados por Corrida</h2><br />
        </div>

        <img class="imglogo" src="~/Images/aapc.jpg" alt="Grupo AAPC"> <br />

        <HR SIZE=7>
        <div class="objetivo">
            <h3> Objetivos do Grupo:</h3>
            <ol>

                <li> Cuidar da saúde através da prática de exercícios. </li>
                <li> Cuidar da mente realizando uma atividade prazerosa. </li>
                <li> Estar entre amigos. </li>
            </ol>
        </div>
        <HR SIZE=7>

        <!-- <div class="text-center">
        <img src="~\Assets\corrida.jpg" />

     </div>-->
        <!--
    <p>
        <a asp-action="Create">Create New</a>
    </p>-->
        <div class="row">
            <div class="col-md-8">
                <table class="table">

                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Dia)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Horario)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Local)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Dia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Horario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Local)
                </td>

            </tr>
}
                    </tbody>
                </table>
            </div>

            <div class="col-md-4">
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                        </tr>
                        <tr>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <a asp-controller="TreinoTercas" asp-action="Index">Detalhes e Inscrição</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a asp-controller="TreinoQuintas" asp-action="Index">Detalhes e Inscrição</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a asp-controller="TreinoSabadoes" asp-action="Index">Detalhes e Inscrição</a>
                            </td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </body>
<br />
<p style="color:purple"> Nos siga no Instagram!</p>
<a href="https://www.instagram.com/amigos_apaixonados_por_corrida/?hl=pt-br" target="_blank"> <img src="~/Images/instagram.png" WIDTH="50" HEIGHT="50"></a>
<br>
<a href="#top">Voltar ao topo</a>
<style>

    li{
        font-size:large;
    }

    .topo {
        font-size: 35px;
        text-align: center;
        color: green;
    }

    .opc {
        color: black;
        text-align: left;
        font-weight: bold;
    }

    .tableaapc table, th, td {
        color: black;
        font-style: normal;
        text-align: left;
        /*border: double darkgray;*/
        padding: 7px;
        text-align: left;
    }

    .imglogo {
        border-style: double;
        width: 15%;
        display: block;
        margin-left: auto;
        margin-right: auto;
        /*padding-bottom: 30px;*/
    }

    .imgfundo {
        background-image: url('../../wwwroot/Images/aapc.jpg')
    }

    .objetivo {
        color: black;
        font-style: normal;
        text-align: left;
    }
</style>